sudo: required
services:
  - docker

before_install:
  - docker build -t pozz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pozz/react-test npm test

after_success:
  - docker build -t apozzoli/multi-client ./client
  - docker build -t apozzoli/multi-nginx ./nginx
  - docker build -t apozzoli/multi-server ./server
  - docker build -t apozzoli/multi-worker ./worker
  #Login to docker
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  #Push to Dockerhub
  - docker push apozzoli/multi-client
  - docker push apozzoli/multi-nginx  
  - docker push apozzoli/multi-server
  - docker push apozzoli/multi-worker
